model_params:
  name: "VAE"
  M: 50
  N: 50
  hidden_dim: 512
  latent_dim: 128

data_params:
  data_path: "data/"
  batch_size: 5
  val_batch_size: 64
  patch_size: 64
  num_workers: 4

exp_params:
  lr: 0.003
  weight_decay: 0.00005
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0, 1]
  epochs: 20
  gradient_clip_val: 0.8

logging_params:
  save_dir: "logs/"
  name: "VAE"
